version: '3.8'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=RinhaBackend2024Q1
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=200 -c max_wal_size=512 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
  
  
  
#  db:
#    image: postgres:16.1
#    hostname: db
#    environment:
#      - POSTGRES_USER=rinha
#      - POSTGRES_PASSWORD=backend
#      - POSTGRES_DB=RinhaBackend2024Q1
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    command: 'postgres -c max_connections=1000 -c shared_buffers=128MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
#    #command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
#    deploy:
#      resources:
#        limits:
#          # Note que a soma de todos os limites dos serviços
#          # aqui declarados é de 1.5 unidades de CPU e 550MB
#          # de memória. A distribuição feita aqui é apenas
#          # um exemplo – distribua como quiser.
#          cpus: "0.8"
#          # memory: "340MB"
          
    #  db:
    #    image: postgres:16.1
    #    restart: always
    #    environment:
    #      - POSTGRES_USER=postgres
    #      - POSTGRES_PASSWORD=postgres
    #    ports:
    #      - '5432:5432'
    #    volumes:
    #      - db:/var/lib/postgresql/data
    #volumes:
    #  db:
    #    driver: local
    
    #https://geshan.com.np/blog/2021/12/docker-postgres/